### ISSUE TITLE
Creating subfolders with "JSON name field"

### ISSUE THREAD

**Issue by agnoldo** [farling42/obsidian-import-json#11]
Hi Martin,

Thanks for this awesome plugin. It saves us a lot of time when importing bulk data into Obsidian!

Now I faced a situation that I would like to ask you about: is it possible to make the plugin support subfolders inside the "JSON name field"? Suppose I'm going to import a lot of data from a CSV into a vault but I want to create a tree structure for that, with folders and subfolders. I already inserted the names of folders and subfolders on the "JSON name field", using '/' as folder separator (so Obsidian doesn't think I'm escaping anything).

Is is possible to do it?

Thanks!

Arnaldo

**Comment by agnoldo** [comment]
Hi Martin,

I forgot to mention that the plugin is able to create one level of subfolder. My question is if it's possible to create unlimited levels of subfolders encoded in "JSON name field".

Thanks again!

Arnaldo

**Comment by farling42** [comment]
An option to use "/" in name field to create paths has been added in 0.15.0
