### ISSUE TITLE
Support nested name lookups

### ISSUE THREAD

**Issue by Sinled** [farling42/obsidian-import-json#13]
Hi thanks for great plugin.

Would it be possible to specify  path to `name` in json import? It is useful when you are  trying to import from files with several localisations e.g.
```json
[
  {
    "en": { "name": "name_en" },
    "es": { "name": "name_es" }
  }
]
```

Also import files not always have array on top level of `json` file, and may have some meta information besides table data. It would be great to have option with path to data, so you don't need to manually edit json files before import.

**Comment by farling42** [comment]
See #14 for your second suggestion.

**Comment by farling42** [comment]
0.17.0 now supports specifying a path for the "Field to use as Note name".
Each part of the path is separated by "."
