### ISSUE TITLE
Empty folders, no notes

### ISSUE THREAD

**Issue by PaySlipBanSA** [farling42/obsidian-import-json#15]
Hello! :)
I know very little about coding and could be making a pretty obvious mistake! I keep getting a list of empty folders as opposed to notes. Any ideas for me to try? Thank you so much!
Leonie

**Comment by farling42** [comment]
Could you provide the markdown template file that you are using please.
Also, press ctrl-shift-i and see if any errors (in red) are reported in the Console window when you try to import your json file.

**Comment by PaySlipBanSA** [comment]
Hello!!!
This is what I used (created it watching your video).

---
Tag : {{Date}}
---

**Date:**      {{Date}}

**Type:**      {{Type}}

**Title:**     {{Title}}

**Url:**       {{Url}}

**Comment:**   {{Comment}}


| Date    | Type   | Title    | Url        |  Comment        |         
| ------- | -------| -------- |------      |  ---------      | 
|{{Date}} |{{Type}}|{{Title}} | {{Url}}    |  {{Comment}}    |
|

**Comment by farling42** [comment]
Is your source of data JSON or CSV?

In CSV, the column names need to match case with the markdown field names: "Date", "Type", etc.

In JSON, the fields within each record of the array need to match case with the markdown field names.

**Comment by PaySlipBanSA** [comment]
Thanks so much Martin. I'm extracting data from a CSV doc and yes, the titles are in the same case. Is there perhaps something I need to do in the app settings? Unfortunately, I'm a total neanderthal, but I can assure you I have activated the app! hahaha .... :(

**Comment by farling42** [comment]
Next step is to see if there are any unusual errors:

Press ctrl-shift-i to open up the "dev console".
Attempt your import again, and see if any errors (in red) or warnings are reported in the Console window when you try to import your csv file.

**Comment by Celldeth** [comment]
This issue seems similar to mine, the error that i get in console looks like this:

Missing helper: "Divine"
FOR ROW:
[object Object]

I looks like "Divine" might be referencing one of the lines called "Divine Rank" specific to my .csv file I posted more in my Issue.
