### ISSUE TITLE
Accents issue

### ISSUE THREAD

**Issue by pasalomoco** [farling42/obsidian-import-json#16]
I have a problem with the accents when i try to import some data
![image](https://user-images.githubusercontent.com/73989196/174628473-d557a4de-8264-4418-a8ff-e21d5ca0ff86.png)

**Comment by farling42** [comment]
Another case of files being opened or written in ASCII instead of UTF-8 mode.
I'll have a look at where the encoding isn't being handled properly.

**Comment by farling42** [comment]
Are you using two {{ or three {{{ brackets in your handlebars template file?

**Comment by farling42** [comment]
If the problem is in reading a CSV file then I need to fix the code since Papa.parse is missing
```
encoding: "utf-8"
```
(But that should be the default, acccording to the FileReader API that Papaparse uses.)

**Comment by farling42** [comment]
I've just tested using á and í and both CSV and JSON seem to be working properly.

**Comment by farling42** [comment]
Is the data in CSV of JSON files?

**Comment by pasalomocoPacheta** [comment]
It´s ok now, it was an error in my csv. Thank you very much for your answers

**Comment by pasalomocoPacheta** [comment]
> If the problem is in reading a CSV file then I need to fix the code since Papa.parse is missing
> 
> ```
> encoding: "utf-8"
> ```
> 
> (But that should be the default, acccording to the FileReader API that Papaparse uses.)

Exactly

**Comment by farling42** [comment]
> It´s ok now, it was an error in my csv. Thank you very much for your answers

Excellent news!
