### ISSUE TITLE
FR: Public API for other plugin use

### ISSUE THREAD

**Issue by valentine195** [farling42/obsidian-import-json#2]
Hey! I was thinking about adding the ability to specify import templates using handlebars for the TTRPG Statblocks plugin, and realized that you already did the hard work :)

Would it be possible for you to create a generic method I could pass a json file and handlebars template file to, and get back the parsed file?

**Comment by farling42** [comment]
The convertJson routine in my plugin takes a jsonfile which contains an 
array of records and creates many files, one per record in the array.

If that is what is required then I can probably make it an easy exported 
method.

--

If you only require a single record to be processed then it might be 
quicker to grab just the few lines required:

85 (JSON.parse)

88-92 (sets up handlebars)

125 (let body = template(jsondata)).

**Comment by valentine195** [comment]
Yup, basically. The idea would be to pass a file of JSON array of objects and a handlebars file and get back the array of monsters.

**Comment by farling42** [comment]
My version adds the files directly into the vault in a named location; I don't know if you would want them there.

It is only half a dozen lines - the main thing is to initialize the handlebars thing only once per batch. :)

**Comment by valentine195** [comment]
Thanks for the heads up!
