### ISSUE TITLE
A question about "Field to use as Note name"

### ISSUE THREAD

**Issue by seed78** [farling42/obsidian-import-json#20]
When opening the JSON CVS importer, I can define which field to use as Note name. However, how can I add @, for example, in front of the name?

The field in JSON is citationkey. But, I want the name of a note as @citationkey.

**Comment by farling42** [comment]
It isn't possible to add anything to the note name via this module. It will always just use the value of a field as a note name.

**Comment by farling42** [comment]
There might be other ways of adding "@" as a prefix to all the notes in a single directory, maybe even something outside of obsidian and simply a script that runs at the OS level?

**Comment by seed78** [comment]
Got it! Thank you!

**Comment by seed78** [comment]
yes, I use Windows 10 and it seems allow me to use @ in front of a file name. Thanks for asking. 

If the coming version of the JSON/CVS importer can allow the combination of any editing of a Note's name with "Field", it would be very helpful. Some symbol in front of a note's name helps sorting or finding the note with a particular grouping by the symbol.

Thank you aging for the help! I like this Importer.

**Comment by farling42** [comment]
Optional Prefix and/or Suffix for Note (file)names have been added in version 0.20.0

**Comment by seed78** [comment]
I have updated to 0.20.0. It works perfectly!!
