### ISSUE TITLE
Can the importer import new notes while keeping old notes untouched?

### ISSUE THREAD

**Issue by seed78** [farling42/obsidian-import-json#21]
I intend to use this JSON/CSV Importer to import the JSON file in the "Better CSL JSON" format that is exported from a Zotero library with the "Better BibTex" plugin. My Zotero library will expend gradually. This means the JSON file will contain both old and new references. I have experimented this JSON/CSV Importer and found it will overwrite the old note with the same name. Is there a way to use this Importer to import only the new contents in a growing JSON file with new reference feeds? Or, is there a way to bypass the over-writing of the existing notes? Thanks for considering this request or enhancement!

**Comment by farling42** [comment]
There was a thought this morning about whether the module should have an option to NOT overwrite already existing notes.

If this was implemented, it would completely ignore elements in the JSON/CSV file which have already been imported, regardless of any changes that might have occurred in those particular entries. (Tracking changes to existing entries would be far more complicated.)

**Comment by farling42** [comment]
An option to disable overwriting existing notes has been added to 0.21.0
