### ISSUE TITLE
Importing .csv with no result

### ISSUE THREAD

**Issue by Celldeth** [farling42/obsidian-import-json#22]
Hi there, I'm getting no results when trying to import my .csv files. Here are my steps:

download google sheet as .csv file
create note in obsidian with handlebar
create destination folder for import
use json/csv importer designating to each of the previous

The result is a "import finished" in the top right, but no new notes created.

Below is the .csv and .md handlebar note that I used

[Mal'Gama Deities - Deities.csv](https://github.com/farling42/obsidian-import-json/files/9074218/Mal.Gama.Deities.-.Deities.csv)

[Handlebar Template (deity list).md](https://github.com/farling42/obsidian-import-json/files/9074221/Handlebar.Template.deity.list.md)

This is the Error in Console:

Missing helper: "Divine"
FOR ROW:
[object Object]

**Comment by farling42** [comment]
It looks like you have a space in your column name which is causing the problem. If you remove spaces from your column titles and use those new titles in your markdown file then it should work properly. Regards,MartinOn 8 Jul 2022 19:04, Celldeth ***@***.***> wrote:
Hi there, I'm getting no results when trying to import my .csv files. Here are my steps:
download google sheet as .csv file
create note in obsidian with handlebar
create destination folder for import
use json/csv importer designating to each of the previous
The result is a "import finished" in the top right, but no new notes created.
Below is the .csv and .md handlebar note that I used
Mal'Gama Deities - Deities.csv
Handlebar Template (deity list).md
This is the Error in Console:
Missing helper: "Divine"
FOR ROW:
[object Object]

**Comment by Celldeth** [comment]
Just ran it again and it worked after also getting rid of my "." in one of the titles. So strange, i thought i checked that and got the same error. In any case, thank you very much.
