### ISSUE TITLE
How to work with multiple tags?

### ISSUE THREAD

**Issue by seed78** [farling42/obsidian-import-json#23]
I has a JSON file that is exported from Zotero with the "BetterBibTex JSON" format. For a reference, I have one or more tags. 

With the following code, the Importer can import each tag in separative lines.
{{#each tags}}
#{{tag}}
{{/each}}

It will look like the following.
#tag1
#tag2
#tag3

If I want the tags to be arranged as the following, what code should I write?
#tag1, #tag2, #tag3

Thank you!

**Comment by farling42** [comment]
I recently found out about doing something like {{~tag}} or {{tag~}} or 
{{~tag~}}

The tilde ~ means to ignore whitespace generated by the markup.

Also, I think that #each allows use of a count variable, so you can put 
"," before each entry except the first?
