### ISSUE TITLE
Table helper issue

### ISSUE THREAD

**Issue by ZombieSoul** [farling42/obsidian-import-json#28]
This may be user error, but I've run into an issue with the table helper.  

{{table level "0" "cantrip" "1" "1st-level" "2" "2nd-level" "3" "3rd-level" "4" "4th-level" "5" "5th-level" "6" "6th-level" "7" "7th-level" "8" "8th-level" "9" "9th-level"}}

all of those will work except if the level is 0.  

Any Idea on how I can get it to match 0?

Thanks for your time and for the great plugin.

**Comment by farling42** [comment]
This should be fixed in 0.24.0

**Comment by ZombieSoul** [comment]
Confirmed fixed - thank you
