### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by seed78** [farling42/obsidian-import-json#34]
Hi,

I frequently use this plugin to import different JSON files. I wonder whether you could enable HotKeys to open this importer much faster.

Thanks!

**Comment by farling42** [comment]
I will look at this as a separate action from your previous request.
Something was done in my other obsidian plugin which I should be able to use here too.

**Comment by farling42** [comment]
Support for configuring a Hotkey has been added in 0.28.0
