### ISSUE TITLE
Subfolder created despite unchecking 'Allow paths in Note name'

### ISSUE THREAD

**Issue by SpocWeb** [farling42/obsidian-import-json#36]
Hi, first of all thank you for this importer. 
It works quite good, but it seems you are catching only the case of a single Slash /  in a Name, not 2 Slashes. 
Example: 
I imported a File with this Value in the Name Column: 

`Miquel-/Adickesallee/Polizeipräsidium`

This resulted in a Subfolder named `U-Miquel-_Adickesallee` with a File named `Polizeipräsidium.md` 

Expected: a File named `Miquel-_Adickesallee_Polizeipräsidium`

Best Regards...

**Comment by farling42** [comment]
Indeed, it was only replacing the first occurrence of an invalid character in the filename.
Version 0.26.1 now replaces ALL occurrence of invalid characters.
