### ISSUE TITLE
Please support TSV files as well

### ISSUE THREAD

**Issue by ckennedy666** [farling42/obsidian-import-json#4]
Is it possible to support Tab Separated Values (TSV)?  This would be a great help in my attempt to import Traveller RPG sector data from TravellerMap.com in the https://travellermap.com/doc/fileformats#t5-tab-delimited-format.

Thanks.

**Comment by farling42** [comment]
That is probably possible. I think the library I'm using for reading CSV permits any arbitrary separator. Regards,MartinOn 19 Feb 2022 15:10, ckennedy666 ***@***.***> wrote:
Is it possible to support Tab Separated Values (TSV)?  This would be a great help in my attempt to import Traveller RPG sector data from TravellerMap.com in the https://travellermap.com/doc/fileformats#t5-tab-delimited-format.
Thanks.

**Comment by farling42** [comment]
Although I see that TSV has some extra rules, so might not parse properly if your days has blank lines, or other escape characters that CSV allows.

**Comment by ckennedy666** [comment]
Biggest issue with my dataset is the use of { } within the data. But it is only a single curly brace when used, so hopefully it won't conflict with Handlebars.

**Comment by farling42** [comment]
Having checked the functionality within the PapaParse library I'm using to read CSV files, it will auto detect the delimiter from any of comma, tag, pipe, semi-colon, ASCII record separator(30), ASCII unit separator (31).

**Comment by farling42** [comment]
You will need to change the file types in the JSON/CSV file selector dialog to show all files in order to select your TSV file, but otherwise the importer should auto-detect it just fine.

Can you test and let me know if it reads your files?

**Comment by ckennedy666** [comment]
Just tested.  I had to name the file .csv even though it was a TSV file.  It worked!  My very basic test looks good.  It would be nice if the file name filter allowed .tsv as well as .csv.

Thanks.

**Comment by ckennedy666** [comment]
Only thing I see (with 0.8.0), the name of the file must end with .csv for the import to be successful, but it will process TSV file without issue.

Thanks.

**Comment by farling42** [comment]
Will be fixed in 0.11.0
