### ISSUE TITLE
Overwrite feature not working...?

### ISSUE THREAD

**Issue by rustyleaf** [farling42/obsidian-import-json#41]
Hi again @farling42 ,

I have also the overwrite feature is not working on my json imports. They do not overwrite the file... I get an error if teh files already exists?
Have attached screenshots of the import.
![Screenshot 2023-02-28 at 10 37 21](https://user-images.githubusercontent.com/846607/221814264-a17b33ee-ca5f-41d2-9e7f-05c562751f84.jpg)
![Screenshot 2023-02-28 at 10 37 54](https://user-images.githubusercontent.com/846607/221814269-8e4b549a-08e4-45ff-85c1-80134e3bbf7d.jpg)

**Comment by farling42** [comment]
Can you update to the latest version, which handles overwrite slightly differently.

**Comment by rustyleaf** [comment]
Thanks @farling42 .

I updated and restarted Obsidian etc... and still getting the same although i notice that there is "replace" in teh menu but OVERWRITE in the text on the left-handside...

I have attached screenshots...
![Screenshot 2023-02-28 at 12 08 23](https://user-images.githubusercontent.com/846607/221837193-1ad102f0-49eb-4dd6-a9fb-e7bab036e843.jpg)
![Screenshot 2023-02-28 at 12 08 00](https://user-images.githubusercontent.com/846607/221837196-bd1db4a6-2e37-410a-ada8-8af1fe994064.jpg)
![Screenshot 2023-02-28 at 12 07 36](https://user-images.githubusercontent.com/846607/221837207-df6128b2-56a7-48d9-9e16-c3d602143422.jpg)

**Comment by farling42** [comment]
I'll fix the hint text problem.

Is the replace option working for you now?

**Comment by rustyleaf** [comment]
No sadly not... I am still getting the errors as per the screenshot: 
```Error: File already exists```

**Comment by rustyleaf** [comment]
Also can I send you a tip somehow - I tried to send using BAT tokens but that didn't work i don't think...?

**Comment by farling42** [comment]
> Also can I send you a tip somehow - I tried to send using BAT tokens but that didn't work i don't think...?

Any of the "Sponsorship" options in the right-hand bar of https://github.com/farling42/obsidian-import-json

**Comment by farling42** [comment]
Version 0.29.2 changes how existing notes are updated - instead of deleting the note and creating a new note, the existing note is simply modified to contain the new contents.

If this still doesn't work for you, it might be worth checking whether the files have been created whilst Obsidian was running as an administrator (or in some other way that the operating system's file permissions are wrong on the files.)

**Comment by AMGMNPLK** [comment]
I'm having the same problem (MacOS)

**Comment by farling42** [comment]
It might be that the install path you've set in the dialog should not start with a "/".
