### ISSUE TITLE
can I use this to import ChatGPT JSON export files? 

### ISSUE THREAD

**Issue by turnerll** [farling42/obsidian-import-json#43]
can I use this to import ChatGPT JSON export files?

**Comment by farling42** [comment]
Probably, you would have to look at your JSON file to find the name of the fields, which you can then use with your handlebars template file to generate notes from your JSON file.

**Comment by farling42** [comment]
If ChatGPT provides a URL to directly access the JSON, then version 0.30.0 allows you to read that URL directly into the importer.
