### ISSUE TITLE
[Feature Request] Import JSON from URL

### ISSUE THREAD

**Issue by Z3DT** [farling42/obsidian-import-json#44]
I'm looking for a way to import data from a JSON-file that's hosted on a URL, specifically the exported URLs created by PathBuilder2e, a character builder for Pathfinder Second Edition. Example: https://pathbuilder2e.com/json.php?id=178425

It'd be great if the process of importing this data could skip some steps, since you have to manually copy/paste the text on the webpage to a text file, then save it as JSON, and _then_ you can use this tool to import it.

**Comment by farling42** [comment]
Implemented on 0.30.0
