### ISSUE TITLE
Request to incorporate two fields in note name

### ISSUE THREAD

**Issue by macrospecter** [farling42/obsidian-import-json#47]
I have a bunch of data on legal cases, and I would ideally like to name my notes Case-Name_Year. Case-Name and Year are both fields in my csv file. Would it be possible to do this? 

Also, this is such a wonderful and smooth-working plugin!

**Comment by farling42** [comment]
If you can create an additional column in your CSV, derived from those other fields, then you can set "Field to use as Note name" to the name of your new field and that will be used as the name of each note

**Comment by macrospecter** [comment]
Oh, brilliant! I hadn't realized that I could combine non-numerical information from different rows in Google Docs, but so it seems that I can. Thanks again for a great plugin.

**Comment by farling42** [comment]
Yeah, any spreadsheet should simply concatenate strings if you add two cells together.
