### ISSUE TITLE
Plugin Just Not Doing Anything?

### ISSUE THREAD

**Issue by noellecdv0** [farling42/obsidian-import-json#48]
I have been attempting to import a CSV file into bsidian using this plugin. Even though I believe I'm doing everything correctly and the plugin says "Import Finished" whenever I execute it, it never does anything/creates any files and I'm not sure how to troubleshoot what I'm doing wrong since it doesn't throw any error.

**Comment by farling42** [comment]
If you open the console with ctrl-shift-i, can you check if there are any warnings or errors reported.

Also, if you change the filter in the console to "All Levels" instead of "Default Levels", to see if it is reporting any progress when you press the import button.

**Comment by noellecdv0** [comment]
Oh wow, I didn't realize there even was a console! Here's what appears when I click import:
<img width="346" alt="image" src="https://github.com/farling42/obsidian-import-json/assets/98427340/0883dd30-40d5-4d8e-90bd-7ed11803d75c">

**Comment by farling42** [comment]
Is it possible to get a screen capture of your settings for the import?

**Comment by noellecdv0** [comment]
Oh wow, I am so sorry for wasting your time. I figured out the issue was that I had not removed the space in the column name I was using as the File Name attribute. Once I deleted it, the import worked! Thanks so much for going back and forth with me here. I really appreciate it!

**Comment by farling42** [comment]
It's good to know that it is solved :-)
