### ISSUE TITLE
Valid json with curly braces can cause import to fail

### ISSUE THREAD

**Issue by OfficerHalf** [farling42/obsidian-import-json#51]
Valid json that includes a string like `} {` causes the import to fail. The splitting code [here](https://github.com/farling42/obsidian-import-json/blob/master/main.ts#L483) that attempts to process multiple json objects in a single file is the source of the issue.

Instead it might be best to check if the top level of the file is an array, or at least have an option to enable/disable this behavior.

**Comment by farling42** [comment]
Version 0.31.1 now makes it an option to treat the JSON file as having multiple records, rather than automatically assuming so.
