### ISSUE TITLE
Can't Import json

### ISSUE THREAD

**Issue by CyberAnpu** [farling42/obsidian-import-json#52]
Hello,
I am trying to import a JSON file in to Obsidian using the plugin, I am following @Josh Plunkett guide on handlebars, and after pressing import, it says "Import Finished" and nothing changes and nothing is showing up and I'm really lost. I tried to search for a solution but couldn't find anything

**Comment by CyberAnpu** [comment]
![image](https://github.com/farling42/obsidian-import-json/assets/66734188/c6a5278c-fe95-4519-aec7-8edcd40c1bd1)

I'm also adding a photo of the settings I use and the console for reference (the only 2 options not visible in the import settings are the file that I've chosen and the "Import" button)

**Comment by farling42** [comment]
Also, are you certain that your "Test.json" is in the correct format for the chosen markdown file?
Since you haven't specified a "Field containing the data", the plugin assumes that the top-level of your json file contains an array (or a single top-level object).

**Comment by farling42** [comment]
In the console on the right, if you change the logging level from "Default Levels" to "All Levels" (or whatever the "all" selection is labelled), then you might see more information about what is happening.

**Comment by CyberAnpu** [comment]
I am indeed using the same format he used in his video, I just switched to "all levels" in the console and I disabled all of the other plugins and it still gives the same message and doesn't do anything

**Comment by farling42** [comment]
Is it possible to have a copy of your Test.json, so that I can see what the data looks like.

**Comment by CyberAnpu** [comment]
[Test.txt](https://github.com/farling42/obsidian-import-json/files/12568153/Test.txt)

Hi, sorry for the late delay! I have attached the Test file but as a "txt" because github doesn't let me post a json file. but the original is indeed .json

**Comment by farling42** [comment]
You need to tell the importer where to find the data in your JSON file.

In your case, you will need to set the field "Field containing the data" to the string "spell".

The importer will then look at the "spell" field of the top-level JSON object that is defined in the file.

**Comment by CyberAnpu** [comment]
yesssssssssss it worked!!! thank you so so much!!!
