### ISSUE TITLE
JSON-Can Templater or QuickAdd inline code be triggered on import?

### ISSUE THREAD

**Issue by buttonpushertv** [farling42/obsidian-import-json#57]
It seems as though any inline Templater or QuickAdd code in a handlebars template is ignored during the import process.

Is there any way to allow this code to be executed on import?

I imagine it may not be called so that one of those templating processes doesn't overwrite the importer plugin's work, but it would be nice to have the ability to run inline code from those plugins on import as well.

**Comment by buttonpushertv** [comment]
I do have the setting for Templater checked on: "Trigger Templater on new file creation"

So, I think that means it should be firing - at least Templater should. We'll see if they respond to your issue.

Thanks for doing that.

**Comment by farling42** [comment]
The request for the sourcePath should be a separate issue. I know that I currently export `SourceFilename` so it might not be too difficult to extend this into a full path (depending on what aspects of the source file JS/Obsidian allow me to access).

**Comment by buttonpushertv** [comment]
And I'm closing this one as well. Once we hear from SilentVoid about how Templater gets triggered, we'll know if there's anything to be done & you can re-open if it's something you will pursue.

Thanks again for the replies & input.

**Comment by farling42** [comment]
SilentVoid has replied to the above linked issue. Can you check it?

**Comment by farling42** [comment]
It is worth noting that if you are having the JSON importer overwrite existing notes then the "create" rule won't be triggered.

**Comment by buttonpushertv** [comment]
Yes. the "Replace" function does not trigger it. However, creating a new set of files will trigger Templater inline code on import/initial creation. Subsequent imports need to have previous file deleted to get the Templater code to trigger again. So, with the caveat: Templater code only gets triggered on creation of non-existing files and will be ignored if replacing exiting files.
