### ISSUE TITLE
Prop contains html and template doesnt escape

### ISSUE THREAD

**Issue by hakdag** [farling42/obsidian-import-json#60]
I have a sample JSON similar to this:

`{
   "id": "1",
   "name": "test",
   "fields": {
       "description": "<p>description</p>"
   }
}
`

And template:

# {{name}} ({{id}})
## Fields
| {{#each fields}} {{@key}} | {{/each}}
| {{#each fields}} - | {{/each}}
| {{#each fields}} {{this}} | {{/each}}

in the template, last line produces description in a table. {{this}} is not escaped. Result is:
<p>description</p>

What should I do?

**Comment by farling42** [comment]
You could try `{{{this}}}` using three brackets instead of only 2.
I'm not sure what you're expecting in your result, since you only show the value of the "description" field.
