### ISSUE TITLE
increment files and more flexible file name options

### ISSUE THREAD

**Issue by the1gofer** [farling42/obsidian-import-json#64]
It would be nice to have the option to increment the file name if it already exists.  Sometimes, with the current options, I end up with duplicate file names, and for query reasons, I want to keep separate files for them.   Right now that's not possible. 

It would also be nice if we could somehow use more than one field for the file name.

**Comment by farling42** [comment]
Version 0.35.0 provides a new checkbox "Add suffix on duplicate Note Names".
It also allows a Note name syntax similar to "${country}-${city}" if you want a name made from more than one field.

**Comment by the1gofer** [comment]
great, thank you!
